add german translation
davidtakac/bura pull request #39
Opened 2024-05-01 18:57 UTC by Stzyxh

yes

2024-05-05 21:43 UTC, SehrGuterCode requested changes
There are a few things that should be fixed here (Source: I'm a German native speaker)

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_error_failed_to_download">der Download der Vorhersage ist fehlgeschlagen. Stellen Sie eine Internetverbindung her und versuchen Sie es erneut.</string>
Should be `Der` instead of `der` (beginning of sentence)

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_error_outdated">ihre Vorhersagedaten sind abgelaufen. Verbinden Sie sich mit dem Internet und versuchen Sie es erneut.</string>
Should be `Ihre` instead of `ihre` (beginning of sentence)

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_error_no_selected_place">kein ausgewählter Ort</string>
Should be `Kein` instead of `kein`, and there should be a `.` at the end of the sentence (which is present in the original string as well)

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_btn_try_again">erneut versuchen</string>
Should be `Erneut` instead of `erneut`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_btn_select_place">Ort auswählen </string>
There shouldn't be an empty space at the end

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_btn_dialog_cancel">abbrechen</string>
Should be `Abbrechen` instead of `abbrechen`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="place_picker_hint_search">Orte dursuchen…</string>
Should be `durchsuchen` instead of `dursuchen`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="place_picker_error_no_saved_places">keine gespeicherte Orte</string>
Should be `Keine` instead of `keine`, and there should be a `.` at the end

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_screen_label_pressure_unit_inhg">Zoll von Quecksilber</string>
Do we need the `von` here? I've never heard of this unit in german but according to google, it's `Zoll Quecksilber`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_screen_label_light">hell</string>
Should be `Hell` instead of `hell`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="settings_screen_label_vis_unit_km">Killometer</string>
Should be `Kilometer` instead of `Killometer`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="date_time_now">jetzt</string>
Should be capitalized

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="date_time_today">heute</string>
Should be capitalized

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="pressure_trend_steady">Ständig</string>
Should be `Konstant`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="feels_like_value_actual">Tatsächliche %s</string>
Should be `Tatsächlich %s`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="feels_like_cooler_than_actual">Durch den Wind ist es kühler geworden.</string>
This should indicate that it describes the felt temperature instead of the actual, like in the English strings.
Example: `Durch den Wind fühlt es sich kühler an.`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="uv_index">UV Index</string>
Should be `UV-Index`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="uv_index_protection_value_from_until">Verwenden Sie Sonnenschutzmittel %1$s-%2$s.</string>
Should be `Verwenden Sie Sonnenschutz von %1$s bis %2$s.`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="uv_index_protection_value_from">Verwenden Sie einen Sonnenschutz von %s.</string>
Should (probably) be `Verwenden Sie Sonnenschutz ab %s.`, depending on the context

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="uv_index_protection_value_until">Sonnenschutz bis %s verwenden.</string>
Should be `Verwenden Sie Sonnenschutz bis %s.`

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="vis_description_very_low">Sehr eingeschränkte Sicht.</string>
`Stark eingeschränkte Sicht.` would probably sound better here

2024-05-05 21:43 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="wind_value_gusts_at">Gusts at %s.</string>
Should be translated: `Böen um %s.`

2024-05-07 13:20 UTC, Stzyxh commented on app/src/main/res/values-de/strings.xml
> +    <string name="general_btn_select_place">Ort auswählen </string>
Thx i fixed all that things

2024-05-08 08:21 UTC, davidtakac commented
Thank you for collaborating on this. Since I'm not a native speaker, I'll wait for @SehrGuterCode's approval before merging. I can also fix the merge conflicts due to recently merged Chinese (Simplified).

2024-05-08 20:35 UTC, SehrGuterCode requested changes

2024-05-08 20:35 UTC, SehrGuterCode commented on app/src/main/java/com/davidtakac/bura/common/Locale.kt
> +    locale.forLanguageTag("de"),
Is this supposed to be lowercased?

2024-05-08 20:35 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="uv_index_risk_extreme">Extreme</string>
Should be `Extrem`

2024-05-08 20:35 UTC, SehrGuterCode commented on app/src/main/res/values-de/strings.xml
> +    <string name="place_picker_error_no_saved_places">Keine gespeicherte Orte</string>
There should be a `.` at the end of the sentence here

2024-05-09 13:06 UTC, SehrGuterCode approved these changes
LGTM!

2024-05-09 14:11 UTC, merged